"""Auto migration

Revision ID: a8c81fc088c8
Revises: ac4a38f90cf4
Create Date: 2025-08-15 12:18:00.835059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8c81fc088c8'
down_revision = 'ac4a38f90cf4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###