"""Auto migration

Revision ID: ac4a38f90cf4
Revises: a119ef01dae9
Create Date: 2025-08-15 12:17:03.088520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4a38f90cf4'
down_revision = 'a119ef01dae9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###